### ISSUE TITLE
cant dump jellyseer config using buildarr

### ISSUE THREAD

**Issue by Dialgatrainer02** [buildarr/buildarr-jellyseerr#35]
when i try to use buildarr to dump a jellyseerr config it fails with the error message after giving it the api key
```
buildarr -l ERROR jellyseerr dump-config http://192.168.0.112:5055

Jellyseerr instance API key: 
Traceback (most recent call last):
  File "/usr/local/bin/buildarr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/buildarr_jellyseerr/cli.py", line 102, in dump_config
    JellyseerrManager()
  File "/usr/local/lib/python3.9/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
    return instance_config.from_remote(secrets)
  File "/usr/local/lib/python3.9/site-packages/buildarr_jellyseerr/config/__init__.py", line 177, in from_remote
    settings=JellyseerrSettings.from_remote(secrets),
  File "/usr/local/lib/python3.9/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
  File "/usr/local/lib/python3.9/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
  File "/usr/local/lib/python3.9/site-packages/buildarr_jellyseerr/config/settings/services/radarr.py", line 369, in from_remote
    definitions={
  File "/usr/local/lib/python3.9/site-packages/buildarr_jellyseerr/config/settings/services/radarr.py", line 370, in <dictcomp>
    api_service["name"]: Radarr._from_remote(api_service)
  File "/usr/local/lib/python3.9/site-packages/buildarr_jellyseerr/config/settings/services/radarr.py", line 140, in _from_remote
    **cls.get_local_attrs(remote_map=cls._get_remote_map(), remote_attrs=remote_attrs),
  File "/usr/local/lib/python3.9/site-packages/buildarr/config/base.py", line 234, in get_local_attrs
    remote_attr = remote_attrs[remote_attr_name]
KeyError: 'baseUrl'
```

**Comment by Bluscrn** [comment]
I know this is late, but I had this issue also. The problem seems to be the "URL Base" field under the Radar service in Jellyseerr. I attempted to add a URL Base, but Jellyseer failed to connect with any addition on my instance and would not allow me to save the configuration. After attempting this, I made sure to delete everything from that field, including any blank spaces, and ran buildarr jellyseerr dump-config again to see if there was any change, this fixed my issue.

I believe that the field probably had a non-printing character in it from either the initial addition of the radarr service, or I inserted a space in that field without knowing it.
